[package]
name = "untouch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.114"
input = "0.7.1"
regex = "1"
clap = {version = "3.0.14", features = ["derive"] }
